language: csharp
solution: src/Reko-decompiler.sln
sudo: required

#addons:
#  apt:
#    sources:
#      - sourceline: 'ppa:ubuntu-toolchain-r/test'
#    packages:
#      - gcc-7
#      - g++-7

cache:
  directories:
    - $HOME/apt_cache
  before_cache:
    - sudo apt-get autoclean
    - sudo cp -R /var/cache/apt/. $HOME/apt_cache/
    - sudo chown -R travis:travis $HOME/apt_cache

before_install:
  - sudo cp -R $HOME/apt_cache/. /var/cache/apt/
  - sudo chown -R root:root /var/cache/apt
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq
  - sudo apt-get install -y gcc-7-multilib g++-7-multilib
  - mkdir -p $HOME/prefix/bin
  - ln -s /usr/bin/gcc-7 $HOME/prefix/bin/gcc
  - ln -s /usr/bin/g++-7 $HOME/prefix/bin/g++
  - source .travis_env
  - mkdir -p $HOME/capstone
  - pushd $HOME/capstone
  - wget https://github.com/aquynh/capstone/archive/3.0.4.tar.gz
  - tar -xf 3.0.4.tar.gz
  - cd capstone*
  - DESTDIR=$HOME/prefix make install -j $(grep processor /proc/cpuinfo | wc -l)
  - export PKG_CONFIG_PATH="$HOME/prefix/usr/lib/pkgconfig:$PKG_CONFIG_PATH"
  - popd

install:
  - nuget restore src/Reko-decompiler.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - source .travis_env
  - msbuild /version
  - msbuild /p:Configuration=TravisRelease /p:Platform=x86 src/Reko-decompiler.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/tools/c2xml/bin/TravisRelease/c2xml.exe -exclude=UserInterface,FailedTests
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/UnitTests/bin/x64/TravisRelease/Reko.UnitTests.dll -exclude=UserInterface,FailedTests
  - python ./subjects/regressionTests.py --check-output --platform=x86 --configuration=TravisRelease
