language: csharp
solution: src/Reko-decompiler.sln
sudo: required

#addons:
#  apt:
#    sources:
#      - sourceline: 'ppa:ubuntu-toolchain-r/test'
#    packages:
#      - gcc-7
#      - g++-7

cache:
  directories:
    - $HOME/apt_cache

before_install:
  - source .travis_env
  - before_install

install:
  - nuget restore src/Reko-decompiler.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner

script:
  - source .travis_env
  - msbuild /version
  - msbuild /p:Configuration=TravisRelease /p:Platform=x64 src/Reko-decompiler.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/tools/c2xml/bin/TravisRelease/c2xml.exe -exclude=UserInterface,FailedTests
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./src/UnitTests/bin/x64/TravisRelease/Reko.UnitTests.dll -exclude=UserInterface,FailedTests
  - python ./subjects/regressionTests.py --check-output --platform=x64 --configuration=TravisRelease
