version: 0.7.2.{build}

init: 
  - git config --global core.autocrlf true 

configuration: Debug

build:
  project: src/Reko-decompiler.sln
  verbosity: normal

test_script:
  - nunit-console.exe ./src/tools/c2xml/bin/Debug/c2xml.exe -exclude=UserInterface,FailedTests /framework:net-4.5
  - nunit-console.exe ./src/UnitTests/bin/x64/Debug/Reko.UnitTests.dll -exclude=UserInterface,FailedTests /framework:net-4.5
