version: 0.7.2.{build}

init: 
  - git config --global core.autocrlf true 

configuration: Release

build:
  project: src/Reko-decompiler.sln
  verbosity: normal

environment:
  artifacts_dir: bin

after_build:
  - ps : >-
        $shortHash = $env:APPVEYOR_REPO_COMMIT.Substring(0, 10);
        $version = $env:APPVEYOR_BUILD_VERSION;
        ;
        mkdir $env:artifacts_dir;
        "[after_build] compressing WindowsDecompiler...";
        7z a $env:artifacts_dir/WindowsDecompiler-$version-$shortHash.zip ./src/Drivers/WindowsDecompiler/bin/$env:CONFIGURATION/.;
        "[after_build] compressing CmdLine...";
        7z a $env:artifacts_dir/CmdLine-$version-$shortHash.zip ./src/Drivers/CmdLine/bin/$env:CONFIGURATION/.;
        mv ./src/WixInstaller/bin/$env:CONFIGURATION/*.msi ./$env:artifacts_dir/;
        ;
        $filePath = $env:artifacts_dir + "/*.msi";
        $item = Get-Item $filePath;
        $newPath = $item.DirectoryName + "/" + $item.BaseName + "-" + $shortHash + ".msi";
        "[after_build] renaming $filePath -> $newPath";
        mv $filePath $newPath;

test_script:
  - cmd: nunit-console-x86.exe ./src/tools/c2xml/bin/%CONFIGURATION%/c2xml.exe -exclude=UserInterface,FailedTests /framework:net-4.5
  - cmd: nunit-console-x86.exe ./src/UnitTests/bin/%CONFIGURATION%/Reko.UnitTests.dll -exclude=UserInterface,FailedTests /framework:net-4.5
  - cmd: python ./subjects/regressionTests.py --check-output --configuration=%CONFIGURATION%

artifacts:
  - path: bin/*.msi
    name: Reko installer
  - path: bin/WindowsDecompiler-*.zip
    name: Reko WinForms driver
  - path: bin/CmdLine-*.zip
    name: Reko CmdLine driver
