version: 0.7.2.{build}

init: 
  - git config --global core.autocrlf true 

configuration: Release

build:
  project: src/Reko-decompiler.sln
  verbosity: normal

environment:
  reko_setup: src/WixInstaller/bin/$(configuration)/*.msi

after_build:
  - ps: >-
        $shortHash = $env:APPVEYOR_REPO_COMMIT.Substring(0, 10);
        $filePath = $env:reko_setup;
        $item = Get-Item $filePath;
        $newPath = $item.DirectoryName;
        $newPath+= [System.IO.Path]::DirectorySeparatorChar;
        $newPath+= $item.BaseName + "-" + $shortHash + ".msi";
        "$filePath -> $newPath";
        Move-Item $filePath $newPath;
  - cmd: 7z a ./src/Drivers/WindowsDecompiler/bin/%CONFIGURATION%/WindowsDecompiler.7z src/Drivers/WindowsDecompiler/bin/%CONFIGURATION%/.
  - cmd: 7z a ./src/Drivers/CmdLine/bin/%CONFIGURATION%/CmdLine.7z src/Drivers/CmdLine/bin/%CONFIGURATION%/.

test_script:
  - cmd: nunit-console-x86.exe ./src/tools/c2xml/bin/%CONFIGURATION%/c2xml.exe -exclude=UserInterface,FailedTests /framework:net-4.5
  - cmd: nunit-console-x86.exe ./src/UnitTests/bin/%CONFIGURATION%/Reko.UnitTests.dll -exclude=UserInterface,FailedTests /framework:net-4.5
  - cmd: python ./subjects/regressionTests.py --check-output --configuration=%CONFIGURATION%

artifacts:
  - path: src/WixInstaller/bin/$(configuration)/*.msi
    name: Reko installer
  - path: src/Drivers/WindowsDecompiler/bin/%CONFIGURATION%/WindowsDecompiler.7z
    name: Reko WinForms driver
  - path: src/Drivers/CmdLine/bin/%CONFIGURATION%/CmdLine.7z
    name: Reko CmdLine driver
