version: 0.7.2.{build}

init: 
  - git config --global core.autocrlf true 

configuration: Release

build:
  project: src/Reko-decompiler.sln
  verbosity: normal

environment:
  reko_setup: src/WixInstaller/bin/$(configuration)/*.msi

after_build:
  - ps: >-
        $filePath = $env:reko_setup
        $filePathWe = (Split-Path -Path $filePath -Leaf).Split(".")[0];
        $newPath = $filePathWe + $env:APPVEYOR_REPO_COMMIT + ".msi"
        Move-Item $filePath $newPath

test_script:
  - cmd: nunit-console-x86.exe ./src/tools/c2xml/bin/%CONFIGURATION%/c2xml.exe -exclude=UserInterface,FailedTests /framework:net-4.5
  - cmd: nunit-console-x86.exe ./src/UnitTests/bin/%CONFIGURATION%/Reko.UnitTests.dll -exclude=UserInterface,FailedTests /framework:net-4.5

artifacts:
  - path: src/WixInstaller/bin/$(configuration)/*.msi
    name: Reko installer