name: Reko

on:
  push:
    branches: [ netStandard ]
  pull_request:
    branches: [ netStandard ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: macos-latest
            build_config: UnixRelease
            test_config: Release
          - os: ubuntu-latest
            build_config: UnixRelease
            test_config: Release
          - os: windows-latest
            build_config: Release
            test_config: Release
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.404
    - name: Install dependencies
      shell: bash
      run: |
        if [ "$RUNNER_OS" == "Linux" ]; then
          sudo apt-get install libcapstone-dev
        elif [ "$RUNNER_OS" == "macOS" ]; then
          brew install capstone
        fi
    - name: Build
      shell: bash
      env:
        BUILD_CONFIG: ${{ matrix.build_config }}
      run: dotnet msbuild -p:Platform=x64 -p:Configuration=$BUILD_CONFIG -t:build_solution -m ./src/BuildTargets/BuildTargets.csproj
    - name: Unit Tests
      shell: bash
      env:
        TEST_CONFIG: ${{ matrix.test_config }}
      run: dotnet msbuild -p:Platform=x64 -p:Configuration=$TEST_CONFIG -t:run_unit_tests -m ./src/BuildTargets/BuildTargets.csproj
    - name: Regression Tests
      shell: bash
      env:
        TEST_CONFIG: ${{ matrix.test_config }}
      run: dotnet msbuild -p:Platform=x64 -p:Configuration=$TEST_CONFIG -t:run_regressions -m ./src/BuildTargets/BuildTargets.csproj
